document.writeln("<script type=\"text/javascript\">");
document.writeln("var sc_project=12934954; ");
document.writeln("var sc_invisible=1; ");
document.writeln("var sc_security=\"9fefbe04\"; ");
document.writeln("</script>");
document.writeln("<script type=\"text/javascript\"");
document.writeln("src=\"https://www.statcounter.com/counter/counter.js\" async></script>");
document.writeln("<noscript><div class=\"statcounter\"><a title=\"Web Analytics Made Easy -");
document.writeln("Statcounter\" href=\"https://statcounter.com/\" target=\"_blank\"><img");
document.writeln("class=\"statcounter\" src=\"https://c.statcounter.com/12934954/0/9fefbe04/1/\"");
document.writeln("alt=\"Web Analytics Made Easy - Statcounter\"");
document.writeln("referrerPolicy=\"no-referrer-when-downgrade\"></a></div></noscript>");
document.writeln("<!-- End of Statcounter Code -->");
document.writeln(""); 
